
language: python
#cache: pip
#virtualenv:
#  system_site_packages: true
# from https://docs.travis-ci.com/user/languages/python/
python:
  - "3.5"

compiler:
        - clang
        - gcc
#cache:
#  directories:
#    - setup

#before_install:
#  - sudo apt-get update
script: 
  - python -m pip install --upgrade pip setuptools
#  - python3.7 --version
  - sudo ./install.sh
#script:
#  - ./test.sh
#after_success:
#  — coveralls

# dosent work. Travis will not get the installed files. GR
#script:
#  - python --version
#  - python simple.py
#  - python3.5 ./test/run.py
#  - python2.7 ./test/run.py
#  - pwd
#  - python ./test/run.py
#  - python ./db/test.py
#  - python --version