

CC=gcc

vector: vector_array.c
	@echo "making vector"
	$(CC) -o test_bin/vector vector_array.c

hash: hash_table.c
	@echo "making hash_table"
	$(CC) -o test_bin/hash_table hash_table.c


all:
	make vector
	make hash